language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aelxan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aelxan/react-test npm test

after_success:
  - docker build -t aelxan/multi-client ./client
  - docker build -t aelxan/multi-nginx ./nginx
  - docker build -t aelxan/multi-server ./server
  - docker build -t aelxan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing to Docker Hub
  - docker push aelxan/multi-client
  - docker push aelxan/multi-nginx
  - docker push aelxan/multi-server
  - docker push aelxan/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-063396849172
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
